XIncludeFile "stream.pb"
XIncludeFile "resource.pb"
XIncludeFile "json.pb"
XIncludeFile "keyboard.pb"
XIncludeFile "enum.pb"

IncludeFile "WebView2.pbi"
IncludeFile "WebView2EnvironmentOptions.pb"
IncludeFile "WebView2Loader.pbi"
IncludeFile "WebView2_Helper.pb"
IncludeFile "PB_Host_Object.pb"
