;Generated by PB Type Library Importer Version: 1.0
;SDK: 1.0.2365.46

;- ICoreWebView2AcceleratorKeyPressedEventArgs

DataSection
	IID_ICoreWebView2AcceleratorKeyPressedEventArgs:
	Data.l $9F760F8A
	Data.w $FB79, $42BE
	Data.b $99, $90, $7B, $56, $90, $F, $A9, $C7
EndDataSection


;- ICoreWebView2AcceleratorKeyPressedEventArgs2

DataSection
	IID_ICoreWebView2AcceleratorKeyPressedEventArgs2:
	Data.l $3B2C8C8
	Data.w $7799, $4E34
	Data.b $BD, $66, $ED, $26, $AA, $85, $F2, $BF
EndDataSection


;- ICoreWebView2AcceleratorKeyPressedEventHandler

DataSection
	IID_ICoreWebView2AcceleratorKeyPressedEventHandler:
	Data.l $B29C7E28
	Data.w $FA79, $41A8
	Data.b $8E, $44, $65, $81, $1C, $76, $DC, $B2
EndDataSection


;- ICoreWebView2Controller

DataSection
	IID_ICoreWebView2Controller:
	Data.l $4D00C0D1
	Data.w $9434, $4EB6
	Data.b $80, $78, $86, $97, $A5, $60, $33, $4F
EndDataSection


;- ICoreWebView2ZoomFactorChangedEventHandler

DataSection
	IID_ICoreWebView2ZoomFactorChangedEventHandler:
	Data.l $B52D71D6
	Data.w $C4DF, $4543
	Data.b $A9, $C, $64, $A3, $E6, $F, $38, $CB
EndDataSection


;- ICoreWebView2MoveFocusRequestedEventHandler

DataSection
	IID_ICoreWebView2MoveFocusRequestedEventHandler:
	Data.l $69035451
	Data.w $6DC7, $4CB8
	Data.b $9B, $CE, $B2, $BD, $70, $AD, $28, $9F
EndDataSection


;- ICoreWebView2MoveFocusRequestedEventArgs

DataSection
	IID_ICoreWebView2MoveFocusRequestedEventArgs:
	Data.l $2D6AA13B
	Data.w $3839, $4A15
	Data.b $92, $FC, $D8, $8B, $3C, $D, $9C, $9D
EndDataSection


;- ICoreWebView2FocusChangedEventHandler

DataSection
	IID_ICoreWebView2FocusChangedEventHandler:
	Data.l $5EA24BD
	Data.w $6452, $4926
	Data.b $90, $14, $4B, $82, $B4, $98, $13, $5D
EndDataSection


;- ICoreWebView2

DataSection
	IID_ICoreWebView2:
	Data.l $76ECEACB
	Data.w $462, $4D94
	Data.b $AC, $83, $42, $3A, $67, $93, $77, $5E
EndDataSection


;- ICoreWebView2Settings

DataSection
	IID_ICoreWebView2Settings:
	Data.l $E562E4F0
	Data.w $D7FA, $43AC
	Data.b $8D, $71, $C0, $51, $50, $49, $9F, $0
EndDataSection


;- ICoreWebView2NavigationStartingEventHandler

DataSection
	IID_ICoreWebView2NavigationStartingEventHandler:
	Data.l $9ADBE429
	Data.w $F36D, $432B
	Data.b $9D, $DC, $F8, $88, $1F, $BD, $76, $E3
EndDataSection


;- ICoreWebView2NavigationStartingEventArgs

DataSection
	IID_ICoreWebView2NavigationStartingEventArgs:
	Data.l $5B495469
	Data.w $E119, $438A
	Data.b $9B, $18, $76, $4, $F2, $5F, $2E, $49
EndDataSection


;- ICoreWebView2HttpRequestHeaders

DataSection
	IID_ICoreWebView2HttpRequestHeaders:
	Data.l $E86CAC0E
	Data.w $5523, $465C
	Data.b $B5, $36, $8F, $B9, $FC, $8C, $8C, $60
EndDataSection


;- ICoreWebView2HttpHeadersCollectionIterator

DataSection
	IID_ICoreWebView2HttpHeadersCollectionIterator:
	Data.l $702FC30
	Data.w $F43B, $47BB
	Data.b $AB, $52, $A4, $2C, $B5, $52, $AD, $9F
EndDataSection


;- ICoreWebView2ContentLoadingEventHandler

DataSection
	IID_ICoreWebView2ContentLoadingEventHandler:
	Data.l $364471E7
	Data.w $F2BE, $4910
	Data.b $BD, $BA, $D7, $20, $77, $D5, $1C, $4B
EndDataSection


;- ICoreWebView2ContentLoadingEventArgs

DataSection
	IID_ICoreWebView2ContentLoadingEventArgs:
	Data.l $C8A1275
	Data.w $9B6B, $4901
	Data.b $87, $AD, $70, $DF, $25, $BA, $FA, $6E
EndDataSection


;- ICoreWebView2SourceChangedEventHandler

DataSection
	IID_ICoreWebView2SourceChangedEventHandler:
	Data.l $3C067F9F
	Data.w $5388, $4772
	Data.b $8B, $48, $79, $F7, $EF, $1A, $B3, $7C
EndDataSection


;- ICoreWebView2SourceChangedEventArgs

DataSection
	IID_ICoreWebView2SourceChangedEventArgs:
	Data.l $31E0E545
	Data.w $1DBA, $4266
	Data.b $89, $14, $F6, $38, $48, $A1, $F7, $D7
EndDataSection


;- ICoreWebView2HistoryChangedEventHandler

DataSection
	IID_ICoreWebView2HistoryChangedEventHandler:
	Data.l $C79A420C
	Data.w $EFD9, $4058
	Data.b $92, $95, $3E, $8B, $4B, $CA, $B6, $45
EndDataSection


;- ICoreWebView2NavigationCompletedEventHandler

DataSection
	IID_ICoreWebView2NavigationCompletedEventHandler:
	Data.l $D33A35BF
	Data.w $1C49, $4F98
	Data.b $93, $AB, $0, $6E, $5, $33, $FE, $1C
EndDataSection


;- ICoreWebView2NavigationCompletedEventArgs

DataSection
	IID_ICoreWebView2NavigationCompletedEventArgs:
	Data.l $30D68B7D
	Data.w $20D9, $4752
	Data.b $A9, $CA, $EC, $84, $48, $FB, $B5, $C1
EndDataSection


;- ICoreWebView2ScriptDialogOpeningEventHandler

DataSection
	IID_ICoreWebView2ScriptDialogOpeningEventHandler:
	Data.l $EF381BF9
	Data.w $AFA8, $4E37
	Data.b $91, $C4, $8A, $C4, $85, $24, $BD, $FB
EndDataSection


;- ICoreWebView2ScriptDialogOpeningEventArgs

DataSection
	IID_ICoreWebView2ScriptDialogOpeningEventArgs:
	Data.l $7390BB70
	Data.w $ABE0, $4843
	Data.b $95, $29, $F1, $43, $B3, $1B, $3, $D6
EndDataSection


;- ICoreWebView2Deferral

DataSection
	IID_ICoreWebView2Deferral:
	Data.l $C10E7F7B
	Data.w $B585, $46F0
	Data.b $A6, $23, $8B, $EF, $BF, $3E, $4E, $E0
EndDataSection


;- ICoreWebView2PermissionRequestedEventHandler

DataSection
	IID_ICoreWebView2PermissionRequestedEventHandler:
	Data.l $15E1C6A3
	Data.w $C72A, $4DF3
	Data.b $91, $D7, $D0, $97, $FB, $EC, $6B, $FD
EndDataSection


;- ICoreWebView2PermissionRequestedEventArgs

DataSection
	IID_ICoreWebView2PermissionRequestedEventArgs:
	Data.l $973AE2EF
	Data.w $FF18, $4894
	Data.b $8F, $B2, $3C, $75, $8F, $4, $68, $10
EndDataSection


;- ICoreWebView2ProcessFailedEventHandler

DataSection
	IID_ICoreWebView2ProcessFailedEventHandler:
	Data.l $79E0AEA4
	Data.w $990B, $42D9
	Data.b $AA, $1D, $F, $CC, $2E, $5B, $C7, $F1
EndDataSection


;- ICoreWebView2ProcessFailedEventArgs

DataSection
	IID_ICoreWebView2ProcessFailedEventArgs:
	Data.l $8155A9A4
	Data.w $1474, $4A86
	Data.b $8C, $AE, $15, $1B, $F, $A6, $B8, $CA
EndDataSection


;- ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler

DataSection
	IID_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler:
	Data.l $B99369F3
	Data.w $9B11, $47B5
	Data.b $BC, $6F, $8E, $78, $95, $FC, $EA, $17
EndDataSection


;- ICoreWebView2ExecuteScriptCompletedHandler

DataSection
	IID_ICoreWebView2ExecuteScriptCompletedHandler:
	Data.l $49511172
	Data.w $CC67, $4BCA
	Data.b $99, $23, $13, $71, $12, $F4, $C4, $CC
EndDataSection


;- ICoreWebView2CapturePreviewCompletedHandler

DataSection
	IID_ICoreWebView2CapturePreviewCompletedHandler:
	Data.l $697E05E9
	Data.w $3D8F, $45FA
	Data.b $96, $F4, $8F, $FE, $1E, $DE, $DA, $F5
EndDataSection


;- ICoreWebView2WebMessageReceivedEventHandler

DataSection
	IID_ICoreWebView2WebMessageReceivedEventHandler:
	Data.l $57213F19
	Data.w $E6, $49FA
	Data.b $8E, $7, $89, $8E, $A0, $1E, $CB, $D2
EndDataSection


;- ICoreWebView2WebMessageReceivedEventArgs

DataSection
	IID_ICoreWebView2WebMessageReceivedEventArgs:
	Data.l $F99A40C
	Data.w $E962, $4207
	Data.b $9E, $92, $E3, $D5, $42, $EF, $F8, $49
EndDataSection


;- ICoreWebView2CallDevToolsProtocolMethodCompletedHandler

DataSection
	IID_ICoreWebView2CallDevToolsProtocolMethodCompletedHandler:
	Data.l $5C4889F0
	Data.w $5EF6, $4C5A
	Data.b $95, $2C, $D8, $F1, $B9, $2D, $5, $74
EndDataSection


;- ICoreWebView2DevToolsProtocolEventReceiver

DataSection
	IID_ICoreWebView2DevToolsProtocolEventReceiver:
	Data.l $B32CA51A
	Data.w $8371, $45E9
	Data.b $93, $17, $AF, $2, $1D, $8, $3, $67
EndDataSection


;- ICoreWebView2DevToolsProtocolEventReceivedEventHandler

DataSection
	IID_ICoreWebView2DevToolsProtocolEventReceivedEventHandler:
	Data.l $E2FDA4BE
	Data.w $5456, $406C
	Data.b $A2, $61, $3D, $45, $21, $38, $36, $2C
EndDataSection


;- ICoreWebView2DevToolsProtocolEventReceivedEventArgs

DataSection
	IID_ICoreWebView2DevToolsProtocolEventReceivedEventArgs:
	Data.l $653C2959
	Data.w $BB3A, $4377
	Data.b $86, $32, $B5, $8A, $DA, $4E, $66, $C4
EndDataSection


;- ICoreWebView2NewWindowRequestedEventHandler

DataSection
	IID_ICoreWebView2NewWindowRequestedEventHandler:
	Data.l $D4C185FE
	Data.w $C81C, $4989
	Data.b $97, $AF, $2D, $3F, $A7, $AB, $56, $51
EndDataSection


;- ICoreWebView2NewWindowRequestedEventArgs

DataSection
	IID_ICoreWebView2NewWindowRequestedEventArgs:
	Data.l $34ACB11C
	Data.w $FC37, $4418
	Data.b $91, $32, $F9, $C2, $1D, $1E, $AF, $B9
EndDataSection


;- ICoreWebView2WindowFeatures

DataSection
	IID_ICoreWebView2WindowFeatures:
	Data.l $5EAF559F
	Data.w $B46E, $4397
	Data.b $88, $60, $E4, $22, $F2, $87, $FF, $1E
EndDataSection


;- ICoreWebView2DocumentTitleChangedEventHandler

DataSection
	IID_ICoreWebView2DocumentTitleChangedEventHandler:
	Data.l $F5F2B923
	Data.w $953E, $4042
	Data.b $9F, $95, $F3, $A1, $18, $E1, $AF, $D4
EndDataSection


;- ICoreWebView2ContainsFullScreenElementChangedEventHandler

DataSection
	IID_ICoreWebView2ContainsFullScreenElementChangedEventHandler:
	Data.l $E45D98B1
	Data.w $AFEF, $45BE
	Data.b $8B, $AF, $6C, $77, $28, $86, $7F, $73
EndDataSection


;- ICoreWebView2WebResourceRequestedEventHandler

DataSection
	IID_ICoreWebView2WebResourceRequestedEventHandler:
	Data.l $AB00B74C
	Data.w $15F1, $4646
	Data.b $80, $E8, $E7, $63, $41, $D2, $5D, $71
EndDataSection


;- ICoreWebView2WebResourceRequestedEventArgs

DataSection
	IID_ICoreWebView2WebResourceRequestedEventArgs:
	Data.l $453E667F
	Data.w $12C7, $49D4
	Data.b $BE, $6D, $DD, $BE, $79, $56, $F5, $7A
EndDataSection


;- ICoreWebView2WebResourceRequest

DataSection
	IID_ICoreWebView2WebResourceRequest:
	Data.l $97055CD4
	Data.w $512C, $4264
	Data.b $8B, $5F, $E3, $F4, $46, $CE, $A6, $A5
EndDataSection


;- ICoreWebView2WebResourceResponse

DataSection
	IID_ICoreWebView2WebResourceResponse:
	Data.l $AAFCC94F
	Data.w $FA27, $48FD
	Data.b $97, $DF, $83, $E, $F7, $5A, $AE, $C9
EndDataSection


;- ICoreWebView2HttpResponseHeaders

DataSection
	IID_ICoreWebView2HttpResponseHeaders:
	Data.l $3C5FF5A
	Data.w $9B45, $4A88
	Data.b $88, $1C, $89, $A9, $F3, $28, $61, $9C
EndDataSection


;- ICoreWebView2WindowCloseRequestedEventHandler

DataSection
	IID_ICoreWebView2WindowCloseRequestedEventHandler:
	Data.l $5C19E9E0
	Data.w $92F, $486B
	Data.b $AF, $FA, $CA, $82, $31, $91, $30, $39
EndDataSection


;- ICoreWebView2_2

DataSection
	IID_ICoreWebView2_2:
	Data.l $9E8F0CF8
	Data.w $E670, $4B5E
	Data.b $B2, $BC, $73, $E0, $61, $E3, $18, $4C
EndDataSection


;- ICoreWebView2WebResourceResponseReceivedEventHandler

DataSection
	IID_ICoreWebView2WebResourceResponseReceivedEventHandler:
	Data.l $7DE9898A
	Data.w $24F5, $40C3
	Data.b $A2, $DE, $D4, $F4, $58, $E6, $98, $28
EndDataSection


;- ICoreWebView2WebResourceResponseReceivedEventArgs

DataSection
	IID_ICoreWebView2WebResourceResponseReceivedEventArgs:
	Data.l $D1DB483D
	Data.w $6796, $4B8B
	Data.b $80, $FC, $13, $71, $2B, $B7, $16, $F4
EndDataSection


;- ICoreWebView2WebResourceResponseView

DataSection
	IID_ICoreWebView2WebResourceResponseView:
	Data.l $79701053
	Data.w $7759, $4162
	Data.b $8F, $7D, $F1, $B3, $F0, $84, $92, $8D
EndDataSection


;- ICoreWebView2WebResourceResponseViewGetContentCompletedHandler

DataSection
	IID_ICoreWebView2WebResourceResponseViewGetContentCompletedHandler:
	Data.l $875738E1
	Data.w $9FA2, $40E3
	Data.b $8B, $74, $2E, $89, $72, $DD, $6F, $E7
EndDataSection


;- ICoreWebView2DOMContentLoadedEventHandler

DataSection
	IID_ICoreWebView2DOMContentLoadedEventHandler:
	Data.l $4BAC7E9C
	Data.w $199E, $49ED
	Data.b $87, $ED, $24, $93, $3, $AC, $F0, $19
EndDataSection


;- ICoreWebView2DOMContentLoadedEventArgs

DataSection
	IID_ICoreWebView2DOMContentLoadedEventArgs:
	Data.l $16B1E21A
	Data.w $C503, $44F2
	Data.b $84, $C9, $70, $AB, $A5, $3, $12, $83
EndDataSection


;- ICoreWebView2CookieManager

DataSection
	IID_ICoreWebView2CookieManager:
	Data.l $177CD9E7
	Data.w $B6F5, $451A
	Data.b $94, $A0, $5D, $7A, $3A, $4C, $41, $41
EndDataSection


;- ICoreWebView2Cookie

DataSection
	IID_ICoreWebView2Cookie:
	Data.l $AD26D6BE
	Data.w $1486, $43E6
	Data.b $BF, $87, $A2, $3, $40, $6, $CA, $21
EndDataSection


;- ICoreWebView2GetCookiesCompletedHandler

DataSection
	IID_ICoreWebView2GetCookiesCompletedHandler:
	Data.l $5A4F5069
	Data.w $5C15, $47C3
	Data.b $86, $46, $F4, $DE, $1C, $11, $66, $70
EndDataSection


;- ICoreWebView2CookieList

DataSection
	IID_ICoreWebView2CookieList:
	Data.l $F7F6F714
	Data.w $5D2A, $43C6
	Data.b $95, $3, $34, $6E, $CE, $2, $D1, $86
EndDataSection


;- ICoreWebView2Environment

DataSection
	IID_ICoreWebView2Environment:
	Data.l $B96D755E
	Data.w $319, $4E92
	Data.b $A2, $96, $23, $43, $6F, $46, $A1, $FC
EndDataSection


;- ICoreWebView2CreateCoreWebView2ControllerCompletedHandler

DataSection
	IID_ICoreWebView2CreateCoreWebView2ControllerCompletedHandler:
	Data.l $6C4819F3
	Data.w $C9B7, $4260
	Data.b $81, $27, $C9, $F5, $BD, $E7, $F6, $8C
EndDataSection


;- ICoreWebView2NewBrowserVersionAvailableEventHandler

DataSection
	IID_ICoreWebView2NewBrowserVersionAvailableEventHandler:
	Data.l $F9A2976E
	Data.w $D34E, $44FC
	Data.b $AD, $EE, $81, $B6, $B5, $7C, $A9, $14
EndDataSection


;- ICoreWebView2_3

DataSection
	IID_ICoreWebView2_3:
	Data.l $A0D6DF20
	Data.w $3B92, $416D
	Data.b $AA, $C, $43, $7A, $9C, $72, $78, $57
EndDataSection


;- ICoreWebView2TrySuspendCompletedHandler

DataSection
	IID_ICoreWebView2TrySuspendCompletedHandler:
	Data.l $F206A7
	Data.w $9D17, $4605
	Data.b $91, $F6, $4E, $8E, $4D, $E1, $92, $E3
EndDataSection


;- ICoreWebView2_4

DataSection
	IID_ICoreWebView2_4:
	Data.l $20D02D59
	Data.w $6DF2, $42DC
	Data.b $BD, $6, $F9, $8A, $69, $4B, $13, $2
EndDataSection


;- ICoreWebView2FrameCreatedEventHandler

DataSection
	IID_ICoreWebView2FrameCreatedEventHandler:
	Data.l $38059770
	Data.w $9BAA, $11EB
	Data.b $A8, $B3, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2FrameCreatedEventArgs

DataSection
	IID_ICoreWebView2FrameCreatedEventArgs:
	Data.l $4D6E7B5E
	Data.w $9BAA, $11EB
	Data.b $A8, $B3, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2Frame

DataSection
	IID_ICoreWebView2Frame:
	Data.l $F1131A5E
	Data.w $9BA9, $11EB
	Data.b $A8, $B3, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2FrameNameChangedEventHandler

DataSection
	IID_ICoreWebView2FrameNameChangedEventHandler:
	Data.l $435C7DC8
	Data.w $9BAA, $11EB
	Data.b $A8, $B3, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2FrameDestroyedEventHandler

DataSection
	IID_ICoreWebView2FrameDestroyedEventHandler:
	Data.l $59DD7B4C
	Data.w $9BAA, $11EB
	Data.b $A8, $B3, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2DownloadStartingEventHandler

DataSection
	IID_ICoreWebView2DownloadStartingEventHandler:
	Data.l $EFEDC989
	Data.w $C396, $41CA
	Data.b $83, $F7, $7, $F8, $45, $A5, $57, $24
EndDataSection


;- ICoreWebView2DownloadStartingEventArgs

DataSection
	IID_ICoreWebView2DownloadStartingEventArgs:
	Data.l $E99BBE21
	Data.w $43E9, $4544
	Data.b $A7, $32, $28, $27, $64, $EA, $FA, $60
EndDataSection


;- ICoreWebView2DownloadOperation

DataSection
	IID_ICoreWebView2DownloadOperation:
	Data.l $3D6B6CF2
	Data.w $AFE1, $44C7
	Data.b $A9, $95, $C6, $51, $17, $71, $43, $36
EndDataSection


;- ICoreWebView2BytesReceivedChangedEventHandler

DataSection
	IID_ICoreWebView2BytesReceivedChangedEventHandler:
	Data.l $828E8AB6
	Data.w $D94C, $4264
	Data.b $9C, $EF, $52, $17, $17, $D, $62, $51
EndDataSection


;- ICoreWebView2EstimatedEndTimeChangedEventHandler

DataSection
	IID_ICoreWebView2EstimatedEndTimeChangedEventHandler:
	Data.l $28F0D425
	Data.w $93FE, $4E63
	Data.b $9F, $8D, $2A, $EE, $C6, $D3, $BA, $1E
EndDataSection


;- ICoreWebView2StateChangedEventHandler

DataSection
	IID_ICoreWebView2StateChangedEventHandler:
	Data.l $81336594
	Data.w $7EDE, $4BA9
	Data.b $BF, $71, $AC, $F0, $A9, $5B, $58, $DD
EndDataSection


;- ICoreWebView2_5

DataSection
	IID_ICoreWebView2_5:
	Data.l $BEDB11B8
	Data.w $D63C, $11EB
	Data.b $B8, $BC, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2ClientCertificateRequestedEventHandler

DataSection
	IID_ICoreWebView2ClientCertificateRequestedEventHandler:
	Data.l $D7175BA2
	Data.w $BCC3, $11EB
	Data.b $85, $29, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2ClientCertificateRequestedEventArgs

DataSection
	IID_ICoreWebView2ClientCertificateRequestedEventArgs:
	Data.l $BC59DB28
	Data.w $BCC3, $11EB
	Data.b $85, $29, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2StringCollection

DataSection
	IID_ICoreWebView2StringCollection:
	Data.l $F41F3F8A
	Data.w $BCC3, $11EB
	Data.b $85, $29, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2ClientCertificateCollection

DataSection
	IID_ICoreWebView2ClientCertificateCollection:
	Data.l $EF5674D2
	Data.w $BCC3, $11EB
	Data.b $85, $29, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2ClientCertificate

DataSection
	IID_ICoreWebView2ClientCertificate:
	Data.l $E7188076
	Data.w $BCC3, $11EB
	Data.b $85, $29, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2_6

DataSection
	IID_ICoreWebView2_6:
	Data.l $499AADAC
	Data.w $D92C, $4589
	Data.b $8A, $75, $11, $1B, $FC, $16, $77, $95
EndDataSection


;- ICoreWebView2_7

DataSection
	IID_ICoreWebView2_7:
	Data.l $79C24D83
	Data.w $9A3, $45AE
	Data.b $94, $18, $48, $7F, $32, $A5, $87, $40
EndDataSection


;- ICoreWebView2PrintSettings

DataSection
	IID_ICoreWebView2PrintSettings:
	Data.l $377F3721
	Data.w $C74E, $48CA
	Data.b $8D, $B1, $DF, $68, $E5, $1D, $60, $E2
EndDataSection


;- ICoreWebView2PrintToPdfCompletedHandler

DataSection
	IID_ICoreWebView2PrintToPdfCompletedHandler:
	Data.l $CCF1EF04
	Data.w $FD8E, $4D5F
	Data.b $B2, $DE, $9, $83, $E4, $1B, $8C, $36
EndDataSection


;- ICoreWebView2_8

DataSection
	IID_ICoreWebView2_8:
	Data.l $E9632730
	Data.w $6E1E, $43AB
	Data.b $B7, $B8, $7B, $2C, $9E, $62, $E0, $94
EndDataSection


;- ICoreWebView2IsMutedChangedEventHandler

DataSection
	IID_ICoreWebView2IsMutedChangedEventHandler:
	Data.l $57D90347
	Data.w $CD0E, $4952
	Data.b $A4, $A2, $74, $83, $A2, $75, $6F, $8
EndDataSection


;- ICoreWebView2IsDocumentPlayingAudioChangedEventHandler

DataSection
	IID_ICoreWebView2IsDocumentPlayingAudioChangedEventHandler:
	Data.l $5DEF109A
	Data.w $2F4B, $49FA
	Data.b $B7, $F6, $11, $C3, $9E, $51, $33, $28
EndDataSection


;- ICoreWebView2_9

DataSection
	IID_ICoreWebView2_9:
	Data.l $4D7B2EAB
	Data.w $9FDC, $468D
	Data.b $B9, $98, $A9, $26, $B, $5E, $D6, $51
EndDataSection


;- ICoreWebView2IsDefaultDownloadDialogOpenChangedEventHandler

DataSection
	IID_ICoreWebView2IsDefaultDownloadDialogOpenChangedEventHandler:
	Data.l $3117DA26
	Data.w $AE13, $438D
	Data.b $BD, $46, $ED, $BE, $B2, $C4, $CE, $81
EndDataSection


;- ICoreWebView2_10

DataSection
	IID_ICoreWebView2_10:
	Data.l $B1690564
	Data.w $6F5A, $4983
	Data.b $8E, $48, $31, $D1, $14, $3F, $EC, $DB
EndDataSection


;- ICoreWebView2BasicAuthenticationRequestedEventHandler

DataSection
	IID_ICoreWebView2BasicAuthenticationRequestedEventHandler:
	Data.l $58B4D6C2
	Data.w $18D4, $497E
	Data.b $B3, $9B, $9A, $96, $53, $3F, $A2, $78
EndDataSection


;- ICoreWebView2BasicAuthenticationRequestedEventArgs

DataSection
	IID_ICoreWebView2BasicAuthenticationRequestedEventArgs:
	Data.l $EF05516F
	Data.w $D897, $4F9E
	Data.b $B6, $72, $D8, $E2, $30, $7A, $3F, $B0
EndDataSection


;- ICoreWebView2BasicAuthenticationResponse

DataSection
	IID_ICoreWebView2BasicAuthenticationResponse:
	Data.l $7023F7D
	Data.w $2D77, $4D67
	Data.b $90, $40, $6E, $7D, $42, $8C, $6A, $40
EndDataSection


;- ICoreWebView2_11

DataSection
	IID_ICoreWebView2_11:
	Data.l $BE78E56
	Data.w $C193, $4051
	Data.b $B9, $43, $23, $B4, $60, $C0, $8B, $DB
EndDataSection


;- ICoreWebView2ContextMenuRequestedEventHandler

DataSection
	IID_ICoreWebView2ContextMenuRequestedEventHandler:
	Data.l $4D3FE1D
	Data.w $AB87, $42FB
	Data.b $A8, $98, $DA, $24, $1D, $35, $B6, $3C
EndDataSection


;- ICoreWebView2ContextMenuRequestedEventArgs

DataSection
	IID_ICoreWebView2ContextMenuRequestedEventArgs:
	Data.l $A1D309EE
	Data.w $C03F, $11EB
	Data.b $85, $29, $2, $42, $AC, $13, $0, $3
EndDataSection


;- ICoreWebView2ContextMenuItemCollection

DataSection
	IID_ICoreWebView2ContextMenuItemCollection:
	Data.l $F562A2F5
	Data.w $C415, $45CF
	Data.b $B9, $9, $D4, $B7, $C1, $E2, $76, $D3
EndDataSection


;- ICoreWebView2ContextMenuItem

DataSection
	IID_ICoreWebView2ContextMenuItem:
	Data.l $7AED49E3
	Data.w $A93F, $497A
	Data.b $81, $1C, $74, $9C, $6B, $6B, $6C, $65
EndDataSection


;- ICoreWebView2CustomItemSelectedEventHandler

DataSection
	IID_ICoreWebView2CustomItemSelectedEventHandler:
	Data.l $49E1D0BC
	Data.w $FE9E, $4481
	Data.b $B7, $C2, $32, $32, $4A, $A2, $19, $98
EndDataSection


;- ICoreWebView2ContextMenuTarget

DataSection
	IID_ICoreWebView2ContextMenuTarget:
	Data.l $B8611D99
	Data.w $EED6, $4F3F
	Data.b $90, $2C, $A1, $98, $50, $2A, $D4, $72
EndDataSection


;- ICoreWebView2_12

DataSection
	IID_ICoreWebView2_12:
	Data.l $35D69927
	Data.w $BCFA, $4566
	Data.b $93, $49, $6B, $3E, $D, $15, $4C, $AC
EndDataSection


;- ICoreWebView2StatusBarTextChangedEventHandler

DataSection
	IID_ICoreWebView2StatusBarTextChangedEventHandler:
	Data.l $A5E3B0D0
	Data.w $10DF, $4156
	Data.b $BF, $AD, $3B, $43, $86, $7A, $CA, $C6
EndDataSection


;- ICoreWebView2_13

DataSection
	IID_ICoreWebView2_13:
	Data.l $F75F09A8
	Data.w $667E, $4983
	Data.b $88, $D6, $C8, $77, $3F, $31, $5E, $84
EndDataSection


;- ICoreWebView2Profile

DataSection
	IID_ICoreWebView2Profile:
	Data.l $79110AD3
	Data.w $CD5D, $4373
	Data.b $8B, $C3, $C6, $6, $58, $F1, $7A, $5F
EndDataSection


;- ICoreWebView2_14

DataSection
	IID_ICoreWebView2_14:
	Data.l $6DAA4F10
	Data.w $4A90, $4753
	Data.b $88, $98, $77, $C5, $DF, $53, $41, $65
EndDataSection


;- ICoreWebView2ServerCertificateErrorDetectedEventHandler

DataSection
	IID_ICoreWebView2ServerCertificateErrorDetectedEventHandler:
	Data.l $969B3A26
	Data.w $D85E, $4795
	Data.b $81, $99, $FE, $F5, $73, $44, $DA, $22
EndDataSection


;- ICoreWebView2ServerCertificateErrorDetectedEventArgs

DataSection
	IID_ICoreWebView2ServerCertificateErrorDetectedEventArgs:
	Data.l $12193ED
	Data.w $7C13, $48FF
	Data.b $96, $9D, $A8, $4C, $1F, $43, $2A, $14
EndDataSection


;- ICoreWebView2Certificate

DataSection
	IID_ICoreWebView2Certificate:
	Data.l $C5FB2FCE
	Data.w $1CAC, $4AEE
	Data.b $9C, $79, $5E, $D0, $36, $2E, $AA, $E0
EndDataSection


;- ICoreWebView2ClearServerCertificateErrorActionsCompletedHandler

DataSection
	IID_ICoreWebView2ClearServerCertificateErrorActionsCompletedHandler:
	Data.l $3B40AAC6
	Data.w $ACFE, $4FFD
	Data.b $82, $11, $F6, $7, $B9, $6E, $2D, $5B
EndDataSection


;- ICoreWebView2_15

DataSection
	IID_ICoreWebView2_15:
	Data.l $517B2D1D
	Data.w $7DAE, $4A66
	Data.b $A4, $F4, $10, $35, $2F, $FB, $95, $18
EndDataSection


;- ICoreWebView2FaviconChangedEventHandler

DataSection
	IID_ICoreWebView2FaviconChangedEventHandler:
	Data.l $2913DA94
	Data.w $833D, $4DE0
	Data.b $8D, $CA, $90, $F, $C5, $24, $A1, $A4
EndDataSection


;- ICoreWebView2GetFaviconCompletedHandler

DataSection
	IID_ICoreWebView2GetFaviconCompletedHandler:
	Data.l $A2508329
	Data.w $7DA8, $49D7
	Data.b $8C, $5, $FA, $12, $5E, $4A, $EE, $8D
EndDataSection


;- ICoreWebView2_16

DataSection
	IID_ICoreWebView2_16:
	Data.l $EB34DC9
	Data.w $9F91, $41E1
	Data.b $86, $39, $95, $CD, $59, $43, $90, $6B
EndDataSection


;- ICoreWebView2PrintCompletedHandler

DataSection
	IID_ICoreWebView2PrintCompletedHandler:
	Data.l $8FD80075
	Data.w $ED08, $42DB
	Data.b $85, $70, $F5, $D1, $49, $77, $46, $1E
EndDataSection


;- ICoreWebView2PrintToPdfStreamCompletedHandler

DataSection
	IID_ICoreWebView2PrintToPdfStreamCompletedHandler:
	Data.l $4C9F8229
	Data.w $8F93, $444F
	Data.b $A7, $11, $2C, $D, $FD, $63, $59, $D5
EndDataSection


;- ICoreWebView2_17

DataSection
	IID_ICoreWebView2_17:
	Data.l $702E75D4
	Data.w $FD44, $434D
	Data.b $9D, $70, $1A, $68, $A6, $B1, $19, $2A
EndDataSection


;- ICoreWebView2SharedBuffer

DataSection
	IID_ICoreWebView2SharedBuffer:
	Data.l $B747A495
	Data.w $C6F, $449E
	Data.b $97, $B8, $2F, $81, $E9, $D6, $AB, $43
EndDataSection


;- ICoreWebView2_18

DataSection
	IID_ICoreWebView2_18:
	Data.l $7A626017
	Data.w $28BE, $49B2
	Data.b $B8, $65, $3B, $A2, $B3, $52, $2D, $90
EndDataSection


;- ICoreWebView2LaunchingExternalUriSchemeEventHandler

DataSection
	IID_ICoreWebView2LaunchingExternalUriSchemeEventHandler:
	Data.l $74F712E0
	Data.w $8165, $43A9
	Data.b $A1, $3F, $C, $CE, $59, $7E, $75, $DF
EndDataSection


;- ICoreWebView2LaunchingExternalUriSchemeEventArgs

DataSection
	IID_ICoreWebView2LaunchingExternalUriSchemeEventArgs:
	Data.l $7D1A6C3
	Data.w $7175, $4BA1
	Data.b $93, $6, $E5, $93, $CA, $7, $E4, $6C
EndDataSection


;- ICoreWebView2_19

DataSection
	IID_ICoreWebView2_19:
	Data.l $6921F954
	Data.w $79B0, $437F
	Data.b $A9, $97, $C8, $58, $11, $89, $7C, $68
EndDataSection


;- ICoreWebView2_20

DataSection
	IID_ICoreWebView2_20:
	Data.l $B4BC1926
	Data.w $7305, $11EE
	Data.b $B9, $62, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2_21

DataSection
	IID_ICoreWebView2_21:
	Data.l $C4980DEA
	Data.w $587B, $43B9
	Data.b $81, $43, $3E, $F3, $BF, $55, $2D, $95
EndDataSection


;- ICoreWebView2ExecuteScriptWithResultCompletedHandler

DataSection
	IID_ICoreWebView2ExecuteScriptWithResultCompletedHandler:
	Data.l $1BB5317B
	Data.w $8238, $4C67
	Data.b $A7, $FF, $BA, $F6, $55, $8F, $28, $9D
EndDataSection


;- ICoreWebView2ExecuteScriptResult

DataSection
	IID_ICoreWebView2ExecuteScriptResult:
	Data.l $CE15963
	Data.w $3698, $4DF7
	Data.b $93, $99, $71, $ED, $6C, $DD, $8C, $9F
EndDataSection


;- ICoreWebView2ScriptException

DataSection
	IID_ICoreWebView2ScriptException:
	Data.l $54DAE00
	Data.w $84A3, $49FF
	Data.b $BC, $17, $40, $12, $A9, $B, $C9, $FD
EndDataSection


;- ICoreWebView2_22

DataSection
	IID_ICoreWebView2_22:
	Data.l $DB75DFC7
	Data.w $A857, $4632
	Data.b $A3, $98, $69, $69, $DD, $E2, $6C, $A
EndDataSection


;- ICoreWebView2BrowserProcessExitedEventArgs

DataSection
	IID_ICoreWebView2BrowserProcessExitedEventArgs:
	Data.l $1F00663F
	Data.w $AF8C, $4782
	Data.b $9C, $DD, $DD, $1, $C5, $2E, $34, $CB
EndDataSection


;- ICoreWebView2BrowserProcessExitedEventHandler

DataSection
	IID_ICoreWebView2BrowserProcessExitedEventHandler:
	Data.l $FA504257
	Data.w $A216, $4911
	Data.b $A8, $60, $FE, $88, $25, $71, $28, $61
EndDataSection


;- ICoreWebView2CompositionController

DataSection
	IID_ICoreWebView2CompositionController:
	Data.l $3DF9B733
	Data.w $B9AE, $4A15
	Data.b $86, $B4, $EB, $9E, $E9, $82, $64, $69
EndDataSection


;- ICoreWebView2PointerInfo

DataSection
	IID_ICoreWebView2PointerInfo:
	Data.l $E6995887
	Data.w $D10D, $4F5D
	Data.b $93, $59, $4C, $E4, $6E, $4F, $96, $B9
EndDataSection


;- ICoreWebView2CursorChangedEventHandler

DataSection
	IID_ICoreWebView2CursorChangedEventHandler:
	Data.l $9DA43CCC
	Data.w $26E1, $4DAD
	Data.b $B5, $6C, $D8, $96, $1C, $94, $C5, $71
EndDataSection


;- ICoreWebView2CompositionController2

DataSection
	IID_ICoreWebView2CompositionController2:
	Data.l $B6A3D24
	Data.w $49CB, $4806
	Data.b $BA, $20, $B5, $E0, $73, $4A, $7B, $26
EndDataSection


;- ICoreWebView2CompositionController3

DataSection
	IID_ICoreWebView2CompositionController3:
	Data.l $9570570E
	Data.w $4D76, $4361
	Data.b $9E, $E1, $F0, $4D, $D, $BD, $FB, $1E
EndDataSection


;- ICoreWebView2Controller2

DataSection
	IID_ICoreWebView2Controller2:
	Data.l $C979903E
	Data.w $D4CA, $4228
	Data.b $92, $EB, $47, $EE, $3F, $A9, $6E, $AB
EndDataSection


;- ICoreWebView2Controller3

DataSection
	IID_ICoreWebView2Controller3:
	Data.l $F9614724
	Data.w $5D2B, $41DC
	Data.b $AE, $F7, $73, $D6, $2B, $51, $54, $3B
EndDataSection


;- ICoreWebView2RasterizationScaleChangedEventHandler

DataSection
	IID_ICoreWebView2RasterizationScaleChangedEventHandler:
	Data.l $9C98C8B1
	Data.w $AC53, $427E
	Data.b $A3, $45, $30, $49, $B5, $52, $4B, $BE
EndDataSection


;- ICoreWebView2Controller4

DataSection
	IID_ICoreWebView2Controller4:
	Data.l $97D418D5
	Data.w $A426, $4E49
	Data.b $A1, $51, $E1, $A1, $F, $32, $7D, $9E
EndDataSection


;- ICoreWebView2ControllerOptions

DataSection
	IID_ICoreWebView2ControllerOptions:
	Data.l $12AAE616
	Data.w $8CCB, $44EC
	Data.b $BC, $B3, $EB, $18, $31, $88, $16, $35
EndDataSection


;- ICoreWebView2ControllerOptions2

DataSection
	IID_ICoreWebView2ControllerOptions2:
	Data.l $6C991D8
	Data.w $9E7E, $11ED
	Data.b $A8, $FC, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2ClearBrowsingDataCompletedHandler

DataSection
	IID_ICoreWebView2ClearBrowsingDataCompletedHandler:
	Data.l $E9710A06
	Data.w $1D1D, $49B2
	Data.b $82, $34, $22, $6F, $35, $84, $6A, $E5
EndDataSection


;- ICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandler

DataSection
	IID_ICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandler:
	Data.l $2FAB84B
	Data.w $1428, $4FB7
	Data.b $AD, $45, $1B, $2E, $64, $73, $61, $84
EndDataSection


;- ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler

DataSection
	IID_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler:
	Data.l $4E8A3389
	Data.w $C9D8, $4BD2
	Data.b $B6, $B5, $12, $4F, $EE, $6C, $C1, $4D
EndDataSection


;- ICoreWebView2CustomSchemeRegistration

DataSection
	IID_ICoreWebView2CustomSchemeRegistration:
	Data.l $D60AC92C
	Data.w $37A6, $4B26
	Data.b $A3, $9E, $95, $CF, $E5, $90, $47, $BB
EndDataSection


;- ICoreWebView2DevToolsProtocolEventReceivedEventArgs2

DataSection
	IID_ICoreWebView2DevToolsProtocolEventReceivedEventArgs2:
	Data.l $2DC4959D
	Data.w $1494, $4393
	Data.b $95, $BA, $BE, $A4, $CB, $9E, $BD, $1B
EndDataSection


;- ICoreWebView2Environment2

DataSection
	IID_ICoreWebView2Environment2:
	Data.l $41F3632B
	Data.w $5EF4, $404F
	Data.b $AD, $82, $2D, $60, $6C, $5A, $9A, $21
EndDataSection


;- ICoreWebView2Environment3

DataSection
	IID_ICoreWebView2Environment3:
	Data.l $80A22AE3
	Data.w $BE7C, $4CE2
	Data.b $AF, $E1, $5A, $50, $5, $6C, $DE, $EB
EndDataSection


;- ICoreWebView2Environment4

DataSection
	IID_ICoreWebView2Environment4:
	Data.l $20944379
	Data.w $6DCF, $41D6
	Data.b $A0, $A0, $AB, $C0, $FC, $50, $DE, $D
EndDataSection


;- ICoreWebView2Environment5

DataSection
	IID_ICoreWebView2Environment5:
	Data.l $319E423D
	Data.w $E0D7, $4B8D
	Data.b $92, $54, $AE, $94, $75, $DE, $9B, $17
EndDataSection


;- ICoreWebView2Environment6

DataSection
	IID_ICoreWebView2Environment6:
	Data.l $E59EE362
	Data.w $ACBD, $4857
	Data.b $9A, $8E, $D3, $64, $4D, $94, $59, $A9
EndDataSection


;- ICoreWebView2Environment7

DataSection
	IID_ICoreWebView2Environment7:
	Data.l $43C22296
	Data.w $3BBD, $43A4
	Data.b $9C, $0, $5C, $D, $F6, $DD, $29, $A2
EndDataSection


;- ICoreWebView2Environment8

DataSection
	IID_ICoreWebView2Environment8:
	Data.l $D6EB91DD
	Data.w $C3D2, $45E5
	Data.b $BD, $29, $6D, $C2, $BC, $4D, $E9, $CF
EndDataSection


;- ICoreWebView2ProcessInfosChangedEventHandler

DataSection
	IID_ICoreWebView2ProcessInfosChangedEventHandler:
	Data.l $F4AF0C39
	Data.w $44B9, $40E9
	Data.b $8B, $11, $4, $84, $CF, $B9, $E0, $A1
EndDataSection


;- ICoreWebView2ProcessInfoCollection

DataSection
	IID_ICoreWebView2ProcessInfoCollection:
	Data.l $402B99CD
	Data.w $A0CC, $4FA5
	Data.b $B7, $A5, $51, $D8, $6A, $1D, $23, $39
EndDataSection


;- ICoreWebView2ProcessInfo

DataSection
	IID_ICoreWebView2ProcessInfo:
	Data.l $84FA7612
	Data.w $3F3D, $4FBF
	Data.b $88, $9D, $FA, $D0, $0, $49, $2D, $72
EndDataSection


;- ICoreWebView2Environment9

DataSection
	IID_ICoreWebView2Environment9:
	Data.l $F06F41BF
	Data.w $4B5A, $49D8
	Data.b $B9, $F6, $FA, $16, $CD, $29, $F2, $74
EndDataSection


;- ICoreWebView2Environment10

DataSection
	IID_ICoreWebView2Environment10:
	Data.l $EE0EB9DF
	Data.w $6F12, $46CE
	Data.b $B5, $3F, $3F, $47, $B9, $C9, $28, $E0
EndDataSection


;- ICoreWebView2Environment11

DataSection
	IID_ICoreWebView2Environment11:
	Data.l $F0913DC6
	Data.w $A0EC, $42EF
	Data.b $98, $5, $91, $DF, $F3, $A2, $96, $6A
EndDataSection


;- ICoreWebView2Environment12

DataSection
	IID_ICoreWebView2Environment12:
	Data.l $F503DB9B
	Data.w $739F, $48DD
	Data.b $B1, $51, $FD, $FC, $F2, $53, $F5, $4E
EndDataSection


;- ICoreWebView2Environment13

DataSection
	IID_ICoreWebView2Environment13:
	Data.l $AF641F58
	Data.w $72B2, $11EE
	Data.b $B9, $62, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2GetProcessExtendedInfosCompletedHandler

DataSection
	IID_ICoreWebView2GetProcessExtendedInfosCompletedHandler:
	Data.l $F45E55AA
	Data.w $3BC2, $11EE
	Data.b $BE, $56, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2ProcessExtendedInfoCollection

DataSection
	IID_ICoreWebView2ProcessExtendedInfoCollection:
	Data.l $32EFA696
	Data.w $407A, $11EE
	Data.b $BE, $56, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2ProcessExtendedInfo

DataSection
	IID_ICoreWebView2ProcessExtendedInfo:
	Data.l $AF4C4C2E
	Data.w $45DB, $11EE
	Data.b $BE, $56, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2FrameInfoCollection

DataSection
	IID_ICoreWebView2FrameInfoCollection:
	Data.l $8F834154
	Data.w $D38E, $4D90
	Data.b $AF, $FB, $68, $0, $A7, $27, $28, $39
EndDataSection


;- ICoreWebView2FrameInfoCollectionIterator

DataSection
	IID_ICoreWebView2FrameInfoCollectionIterator:
	Data.l $1BF89E2D
	Data.w $1B2B, $4629
	Data.b $B2, $8F, $5, $9, $9B, $41, $BB, $3
EndDataSection


;- ICoreWebView2FrameInfo

DataSection
	IID_ICoreWebView2FrameInfo:
	Data.l $DA86B8A1
	Data.w $BDF3, $4F11
	Data.b $99, $55, $52, $8C, $EF, $A5, $97, $27
EndDataSection


;- ICoreWebView2EnvironmentOptions

DataSection
	IID_ICoreWebView2EnvironmentOptions:
	Data.l $2FDE08A8
	Data.w $1E9A, $4766
	Data.b $8C, $5, $95, $A9, $CE, $B9, $D1, $C5
EndDataSection


;- ICoreWebView2EnvironmentOptions2

DataSection
	IID_ICoreWebView2EnvironmentOptions2:
	Data.l $FF85C98A
	Data.w $1BA7, $4A6B
	Data.b $90, $C8, $2B, $75, $2C, $89, $E9, $E2
EndDataSection


;- ICoreWebView2EnvironmentOptions3

DataSection
	IID_ICoreWebView2EnvironmentOptions3:
	Data.l $4A5C436E
	Data.w $A9E3, $4A2E
	Data.b $89, $C3, $91, $D, $35, $13, $F5, $CC
EndDataSection


;- ICoreWebView2EnvironmentOptions4

DataSection
	IID_ICoreWebView2EnvironmentOptions4:
	Data.l $AC52D13F
	Data.w $D38, $475A
	Data.b $9D, $CA, $87, $65, $80, $D6, $79, $3E
EndDataSection


;- ICoreWebView2EnvironmentOptions5

DataSection
	IID_ICoreWebView2EnvironmentOptions5:
	Data.l $AE35D64
	Data.w $C47F, $4464
	Data.b $81, $4E, $25, $9C, $34, $5D, $15, $1
EndDataSection


;- ICoreWebView2EnvironmentOptions6

DataSection
	IID_ICoreWebView2EnvironmentOptions6:
	Data.l $57D29CC3
	Data.w $C84F, $42A0
	Data.b $B0, $E2, $EF, $FB, $D5, $E1, $79, $DE
EndDataSection


;- ICoreWebView2Frame2

DataSection
	IID_ICoreWebView2Frame2:
	Data.l $7A6A5834
	Data.w $D185, $4DBF
	Data.b $B6, $3F, $4A, $9B, $C4, $31, $7, $D4
EndDataSection


;- ICoreWebView2FrameNavigationStartingEventHandler

DataSection
	IID_ICoreWebView2FrameNavigationStartingEventHandler:
	Data.l $E79908BF
	Data.w $2D5D, $4968
	Data.b $83, $DB, $26, $3F, $EA, $2C, $1D, $A3
EndDataSection


;- ICoreWebView2FrameContentLoadingEventHandler

DataSection
	IID_ICoreWebView2FrameContentLoadingEventHandler:
	Data.l $D6156F2
	Data.w $D332, $49A7
	Data.b $9E, $3, $7D, $8F, $2F, $EE, $EE, $54
EndDataSection


;- ICoreWebView2FrameNavigationCompletedEventHandler

DataSection
	IID_ICoreWebView2FrameNavigationCompletedEventHandler:
	Data.l $609302AD
	Data.w $E36, $4F9A
	Data.b $A2, $10, $6A, $45, $27, $28, $42, $A9
EndDataSection


;- ICoreWebView2FrameDOMContentLoadedEventHandler

DataSection
	IID_ICoreWebView2FrameDOMContentLoadedEventHandler:
	Data.l $38D9520D
	Data.w $340F, $4D1E
	Data.b $A7, $75, $43, $FC, $E9, $75, $36, $83
EndDataSection


;- ICoreWebView2FrameWebMessageReceivedEventHandler

DataSection
	IID_ICoreWebView2FrameWebMessageReceivedEventHandler:
	Data.l $E371E005
	Data.w $6D1D, $4517
	Data.b $93, $4B, $A8, $F1, $62, $9C, $62, $A5
EndDataSection


;- ICoreWebView2Frame3

DataSection
	IID_ICoreWebView2Frame3:
	Data.l $B50D82CC
	Data.w $CC28, $481D
	Data.b $96, $14, $CB, $4, $88, $95, $E6, $A0
EndDataSection


;- ICoreWebView2FramePermissionRequestedEventHandler

DataSection
	IID_ICoreWebView2FramePermissionRequestedEventHandler:
	Data.l $845D0EDD
	Data.w $8BD8, $429B
	Data.b $99, $15, $48, $21, $78, $9F, $23, $E9
EndDataSection


;- ICoreWebView2PermissionRequestedEventArgs2

DataSection
	IID_ICoreWebView2PermissionRequestedEventArgs2:
	Data.l $74D7127F
	Data.w $9DE6, $4200
	Data.b $87, $34, $42, $D6, $FB, $4F, $F7, $41
EndDataSection


;- ICoreWebView2Frame4

DataSection
	IID_ICoreWebView2Frame4:
	Data.l $188782DC
	Data.w $92AA, $4732
	Data.b $AB, $3C, $FC, $C5, $9F, $6F, $68, $B9
EndDataSection


;- ICoreWebView2Frame5

DataSection
	IID_ICoreWebView2Frame5:
	Data.l $99D199C4
	Data.w $7305, $11EE
	Data.b $B9, $62, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2FrameInfo2

DataSection
	IID_ICoreWebView2FrameInfo2:
	Data.l $56F85CFA
	Data.w $72C4, $11EE
	Data.b $B9, $62, $2, $42, $AC, $12, $0, $2
EndDataSection


;- ICoreWebView2GetNonDefaultPermissionSettingsCompletedHandler

DataSection
	IID_ICoreWebView2GetNonDefaultPermissionSettingsCompletedHandler:
	Data.l $38274481
	Data.w $A15C, $4563
	Data.b $94, $CF, $99, $E, $DC, $9A, $EB, $95
EndDataSection


;- ICoreWebView2PermissionSettingCollectionView

DataSection
	IID_ICoreWebView2PermissionSettingCollectionView:
	Data.l $F5596F62
	Data.w $3DE5, $47B1
	Data.b $91, $E8, $A4, $10, $4B, $59, $6B, $96
EndDataSection


;- ICoreWebView2PermissionSetting

DataSection
	IID_ICoreWebView2PermissionSetting:
	Data.l $792B6ECA
	Data.w $5576, $421C
	Data.b $91, $19, $74, $EB, $B3, $A4, $FF, $B3
EndDataSection


;- ICoreWebView2NavigationCompletedEventArgs2

DataSection
	IID_ICoreWebView2NavigationCompletedEventArgs2:
	Data.l $FDF8B738
	Data.w $EE1E, $4DB2
	Data.b $A3, $29, $8D, $7D, $7B, $74, $D7, $92
EndDataSection


;- ICoreWebView2NavigationStartingEventArgs2

DataSection
	IID_ICoreWebView2NavigationStartingEventArgs2:
	Data.l $9086BE93
	Data.w $91AA, $472D
	Data.b $A7, $E0, $57, $9F, $2B, $A0, $6, $AD
EndDataSection


;- ICoreWebView2NavigationStartingEventArgs3

DataSection
	IID_ICoreWebView2NavigationStartingEventArgs3:
	Data.l $DDFFE494
	Data.w $4942, $4BD2
	Data.b $AB, $73, $35, $B8, $FF, $40, $E1, $9F
EndDataSection


;- ICoreWebView2NewWindowRequestedEventArgs2

DataSection
	IID_ICoreWebView2NewWindowRequestedEventArgs2:
	Data.l $BBC7BAED
	Data.w $74C6, $4C92
	Data.b $B6, $3A, $7F, $5A, $EA, $E0, $3D, $E3
EndDataSection


;- ICoreWebView2NewWindowRequestedEventArgs3

DataSection
	IID_ICoreWebView2NewWindowRequestedEventArgs3:
	Data.l $842BED3C
	Data.w $6AD6, $4DD9
	Data.b $B9, $38, $28, $C9, $66, $67, $AD, $66
EndDataSection


;- ICoreWebView2PermissionRequestedEventArgs3

DataSection
	IID_ICoreWebView2PermissionRequestedEventArgs3:
	Data.l $E61670BC
	Data.w $3DCE, $4177
	Data.b $86, $D2, $C6, $29, $AE, $3C, $B6, $AC
EndDataSection


;- ICoreWebView2PrintSettings2

DataSection
	IID_ICoreWebView2PrintSettings2:
	Data.l $CA7F0E1F
	Data.w $3484, $41D1
	Data.b $8C, $1A, $65, $CD, $44, $A6, $3F, $8D
EndDataSection


;- ICoreWebView2ProcessFailedEventArgs2

DataSection
	IID_ICoreWebView2ProcessFailedEventArgs2:
	Data.l $4DAB9422
	Data.w $46FA, $4C3E
	Data.b $A5, $D2, $41, $D2, $7, $1D, $36, $80
EndDataSection


;- ICoreWebView2Profile2

DataSection
	IID_ICoreWebView2Profile2:
	Data.l $FA740D4B
	Data.w $5EAE, $4344
	Data.b $A8, $AD, $74, $BE, $31, $92, $53, $97
EndDataSection


;- ICoreWebView2Profile3

DataSection
	IID_ICoreWebView2Profile3:
	Data.l $B188E659
	Data.w $5685, $4E05
	Data.b $BD, $BA, $FC, $64, $E, $F, $19, $92
EndDataSection


;- ICoreWebView2Profile4

DataSection
	IID_ICoreWebView2Profile4:
	Data.l $8F4AE680
	Data.w $192E, $4EC8
	Data.b $83, $3A, $21, $CF, $AD, $AE, $F6, $28
EndDataSection


;- ICoreWebView2SetPermissionStateCompletedHandler

DataSection
	IID_ICoreWebView2SetPermissionStateCompletedHandler:
	Data.l $FC77FB30
	Data.w $9C9E, $4076
	Data.b $B8, $C7, $76, $44, $A7, $3, $CA, $1B
EndDataSection


;- ICoreWebView2Profile5

DataSection
	IID_ICoreWebView2Profile5:
	Data.l $2EE5B76E
	Data.w $6E80, $4DF2
	Data.b $BC, $D3, $D4, $EC, $33, $40, $A0, $1B
EndDataSection


;- ICoreWebView2Profile6

DataSection
	IID_ICoreWebView2Profile6:
	Data.l $BD82FA6A
	Data.w $1D65, $4C33
	Data.b $B2, $B4, $3, $93, $2, $C, $C6, $1B
EndDataSection


;- ICoreWebView2Profile7

DataSection
	IID_ICoreWebView2Profile7:
	Data.l $7B4C7906
	Data.w $A1AA, $4CB4
	Data.b $B7, $23, $DB, $9, $F8, $13, $D5, $41
EndDataSection


;- ICoreWebView2ProfileAddBrowserExtensionCompletedHandler

DataSection
	IID_ICoreWebView2ProfileAddBrowserExtensionCompletedHandler:
	Data.l $DF1AAB27
	Data.w $82B9, $4AB6
	Data.b $AA, $E8, $1, $7A, $49, $39, $8C, $14
EndDataSection


;- ICoreWebView2BrowserExtension

DataSection
	IID_ICoreWebView2BrowserExtension:
	Data.l $7EF7FFA0
	Data.w $FAC5, $462C
	Data.b $B1, $89, $3D, $9E, $DB, $E5, $75, $DA
EndDataSection


;- ICoreWebView2BrowserExtensionRemoveCompletedHandler

DataSection
	IID_ICoreWebView2BrowserExtensionRemoveCompletedHandler:
	Data.l $8E41909A
	Data.w $9B18, $4BB1
	Data.b $8C, $DF, $93, $F, $46, $7A, $50, $BE
EndDataSection


;- ICoreWebView2BrowserExtensionEnableCompletedHandler

DataSection
	IID_ICoreWebView2BrowserExtensionEnableCompletedHandler:
	Data.l $30C186CE
	Data.w $7FAD, $421F
	Data.b $A3, $BC, $A8, $EA, $F0, $71, $DD, $B8
EndDataSection


;- ICoreWebView2ProfileGetBrowserExtensionsCompletedHandler

DataSection
	IID_ICoreWebView2ProfileGetBrowserExtensionsCompletedHandler:
	Data.l $FCE16A1C
	Data.w $F107, $4601
	Data.b $8B, $75, $FC, $49, $40, $AE, $25, $D0
EndDataSection


;- ICoreWebView2BrowserExtensionList

DataSection
	IID_ICoreWebView2BrowserExtensionList:
	Data.l $2EF3D2DC
	Data.w $BD5F, $4F4D
	Data.b $90, $AF, $FD, $67, $79, $8F, $C, $2F
EndDataSection


;- ICoreWebView2Profile8

DataSection
	IID_ICoreWebView2Profile8:
	Data.l $FBF70C2F
	Data.w $EB1F, $4383
	Data.b $85, $A0, $16, $3E, $92, $4, $40, $11
EndDataSection


;- ICoreWebView2ProfileDeletedEventHandler

DataSection
	IID_ICoreWebView2ProfileDeletedEventHandler:
	Data.l $DF35055D
	Data.w $772E, $4DBE
	Data.b $B7, $43, $5F, $BF, $74, $A2, $B2, $58
EndDataSection


;- ICoreWebView2Settings2

DataSection
	IID_ICoreWebView2Settings2:
	Data.l $EE9A0F68
	Data.w $F46C, $4E32
	Data.b $AC, $23, $EF, $8C, $AC, $22, $4D, $2A
EndDataSection


;- ICoreWebView2Settings3

DataSection
	IID_ICoreWebView2Settings3:
	Data.l $FDB5AB74
	Data.w $AF33, $4854
	Data.b $84, $F0, $A, $63, $1D, $EB, $5E, $BA
EndDataSection


;- ICoreWebView2Settings4

DataSection
	IID_ICoreWebView2Settings4:
	Data.l $CB56846C
	Data.w $4168, $4D53
	Data.b $B0, $4F, $3, $B6, $D6, $79, $6F, $F2
EndDataSection


;- ICoreWebView2Settings5

DataSection
	IID_ICoreWebView2Settings5:
	Data.l $183E7052
	Data.w $1D03, $43A0
	Data.b $AB, $99, $98, $E0, $43, $B6, $6B, $39
EndDataSection


;- ICoreWebView2Settings6

DataSection
	IID_ICoreWebView2Settings6:
	Data.l $11CB3ACD
	Data.w $9BC8, $43B8
	Data.b $83, $BF, $F4, $7, $53, $71, $4F, $87
EndDataSection


;- ICoreWebView2Settings7

DataSection
	IID_ICoreWebView2Settings7:
	Data.l $488DC902
	Data.w $35EF, $42D2
	Data.b $BC, $7D, $94, $B6, $5C, $4B, $C4, $9C
EndDataSection


;- ICoreWebView2Settings8

DataSection
	IID_ICoreWebView2Settings8:
	Data.l $9E6B0E8F
	Data.w $86AD, $4E81
	Data.b $81, $47, $A9, $B5, $ED, $B6, $86, $50
EndDataSection


;- ICoreWebView2WebResourceRequestedEventArgs2

DataSection
	IID_ICoreWebView2WebResourceRequestedEventArgs2:
	Data.l $9C562C24
	Data.w $B219, $4D7F
	Data.b $92, $F6, $B1, $87, $FB, $BA, $DD, $56
EndDataSection


;- ICoreWebView2File

DataSection
	IID_ICoreWebView2File:
	Data.l $F2C19559
	Data.w $6BC1, $4583
	Data.b $A7, $57, $90, $2, $1B, $E9, $AF, $EC
EndDataSection


;- ICoreWebView2ObjectCollectionView

DataSection
	IID_ICoreWebView2ObjectCollectionView:
	Data.l $F36FD87
	Data.w $4F69, $4415
	Data.b $98, $DA, $88, $8F, $89, $FB, $9A, $33
EndDataSection


;- ICoreWebView2WebMessageReceivedEventArgs2

DataSection
	IID_ICoreWebView2WebMessageReceivedEventArgs2:
	Data.l $6FC7AB7
	Data.w $C90C, $4297
	Data.b $93, $89, $33, $CA, $1, $CF, $6D, $5E
EndDataSection


