;Generated by PB Type Library Importer Version: 1.0

;- ICoreWebView2ExperimentalCompositionControllerInterop

DataSection
	IID_ICoreWebView2ExperimentalCompositionControllerInterop:
	Data.l $4B60F2C9
	Data.w $88BB, $42F4
	Data.b $9C, $4F, $3C, $D, $E, $D1, $70, $72
EndDataSection

Interface ICoreWebView2ExperimentalCompositionControllerInterop Extends IUnknown
	get_UIAProvider(provider.i)
	get_RootVisualTarget(target.i)
	put_RootVisualTarget(target.i)
EndInterface 

;- ICoreWebView2ExperimentalCompositionController3

DataSection
	IID_ICoreWebView2ExperimentalCompositionController3:
	Data.l $B134916B
	Data.w $A104, $4D2A
	Data.b $95, $67, $C2, $FD, $53, $71, $43, $50
EndDataSection

Interface ICoreWebView2ExperimentalCompositionController3 Extends IUnknown
	DragEnter(dataObject.i, keyState.l, point.q, effect.i)
	DragLeave()
	DragOver(keyState.l, point.q, effect.i)
	Drop(dataObject.i, keyState.l, point.q, effect.i)
EndInterface 

;- ICoreWebView2ExperimentalCompositionController4

DataSection
	IID_ICoreWebView2ExperimentalCompositionController4:
	Data.l $E6041D7F
	Data.w $18AC, $4654
	Data.b $A0, $4E, $8B, $3F, $81, $25, $1C, $33
EndDataSection

Interface ICoreWebView2ExperimentalCompositionController4 Extends IUnknown
	get_UIAProvider(provider.i)
	CompilerIf #PB_Compiler_Processor = #PB_Processor_x64
		CreateCoreWebView2PointerInfoFromPointerId(PointerId.l, parentWindow.i, transform.i, pointerInfo.i)
	CompilerElse
		CreateCoreWebView2PointerInfoFromPointerId(PointerId.l, parentWindow.i, transform_COREWEBVIEW2_MATRIX_4X4__11.f, transform_COREWEBVIEW2_MATRIX_4X4__12.f, transform_COREWEBVIEW2_MATRIX_4X4__13.f, transform_COREWEBVIEW2_MATRIX_4X4__14.f, transform_COREWEBVIEW2_MATRIX_4X4__21.f, transform_COREWEBVIEW2_MATRIX_4X4__22.f, transform_COREWEBVIEW2_MATRIX_4X4__23.f, transform_COREWEBVIEW2_MATRIX_4X4__24.f, transform_COREWEBVIEW2_MATRIX_4X4__31.f, transform_COREWEBVIEW2_MATRIX_4X4__32.f, transform_COREWEBVIEW2_MATRIX_4X4__33.f, transform_COREWEBVIEW2_MATRIX_4X4__34.f, transform_COREWEBVIEW2_MATRIX_4X4__41.f, transform_COREWEBVIEW2_MATRIX_4X4__42.f, transform_COREWEBVIEW2_MATRIX_4X4__43.f, transform_COREWEBVIEW2_MATRIX_4X4__44.f, pointerInfo.i)
	CompilerEndIf
EndInterface 

;- COREWEBVIEW2_MATRIX_4X4
Structure COREWEBVIEW2_MATRIX_4X4 Align #PB_Structure_AlignC
	_11.f
	_12.f
	_13.f
	_14.f
	_21.f
	_22.f
	_23.f
	_24.f
	_31.f
	_32.f
	_33.f
	_34.f
	_41.f
	_42.f
	_43.f
	_44.f
EndStructure

;- ICoreWebView2ExperimentalController

DataSection
	IID_ICoreWebView2ExperimentalController:
	Data.l $3413543F
	Data.w $7A0E, $4B56
	Data.b $98, $C1, $7A, $F3, $A3, $74, $16, $CA
EndDataSection

Interface ICoreWebView2ExperimentalController Extends IUnknown
	get_RasterizationScale(scale.i)
	put_RasterizationScale(scale.d)
	get_ShouldDetectMonitorScaleChanges(value.i)
	put_ShouldDetectMonitorScaleChanges(value.l)
	add_RasterizationScaleChanged(eventHandler.i, token.i)
	remove_RasterizationScaleChanged(token.q)
	get_BoundsMode(BoundsMode.i)
	put_BoundsMode(BoundsMode.l)
EndInterface 

;- ICoreWebView2ExperimentalRasterizationScaleChangedEventHandler

DataSection
	IID_ICoreWebView2ExperimentalRasterizationScaleChangedEventHandler:
	Data.l $51560BE0
	Data.w $AD4, $4157
	Data.b $90, $CF, $E6, $DA, $D6, $38, $D8, $AA
EndDataSection

Interface ICoreWebView2ExperimentalRasterizationScaleChangedEventHandler Extends IUnknown
	Invoke(sender.i, args.i)
EndInterface 

;- Enum COREWEBVIEW2_BOUNDS_MODE
#COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS = 0
#COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE = 1

;- ICoreWebView2ExperimentalEnvironment2

DataSection
	IID_ICoreWebView2ExperimentalEnvironment2:
	Data.l $37B54FD4
	Data.w $1AD9, $4C1F
	Data.b $BD, $14, $9D, $AB, $A9, $FD, $EB, $26
EndDataSection

Interface ICoreWebView2ExperimentalEnvironment2 Extends IUnknown
	GetProviderForHwnd(hwnd.i, provider.i)
EndInterface 

;- ICoreWebView2ExperimentalEnvironmentInterop

DataSection
	IID_ICoreWebView2ExperimentalEnvironmentInterop:
	Data.l $79455D4F
	Data.w $D28D, $4C3F
	Data.b $A7, $13, $13, $CA, $39, $3B, $D2, $E4
EndDataSection

Interface ICoreWebView2ExperimentalEnvironmentInterop Extends IUnknown
	GetProviderForHwnd(hwnd.i, provider.i)
EndInterface 

;- ICoreWebView2ExperimentalSettings

DataSection
	IID_ICoreWebView2ExperimentalSettings:
	Data.l $684CBEEF
	Data.w $47BA, $4D4A
	Data.b $99, $F4, $97, $61, $13, $F9, $F1, $A
EndDataSection

Interface ICoreWebView2ExperimentalSettings Extends IUnknown
	get_UserAgent(UserAgent.i)
	put_UserAgent(UserAgent.s)
EndInterface 

;- ICoreWebView2ExperimentalSettings2

DataSection
	IID_ICoreWebView2ExperimentalSettings2:
	Data.l $6CC748D4
	Data.w $51C5, $415C
	Data.b $AC, $97, $77, $A1, $5F, $FE, $D9, $39
EndDataSection

Interface ICoreWebView2ExperimentalSettings2 Extends IUnknown
	get_AreBrowserAcceleratorKeysEnabled(AreBrowserAcceleratorKeysEnabled.i)
	put_AreBrowserAcceleratorKeysEnabled(AreBrowserAcceleratorKeysEnabled.l)
EndInterface 

