;Generated by PB Type Library Importer Version: 1.0

;- ICoreWebView2ExperimentalCompositionControllerInterop

DataSection
	IID_ICoreWebView2ExperimentalCompositionControllerInterop:
	Data.l $4B60F2C9
	Data.w $88BB, $42F4
	Data.b $9C, $4F, $3C, $D, $E, $D1, $70, $72
EndDataSection

Interface ICoreWebView2ExperimentalCompositionControllerInterop Extends IUnknown
	get_UIAProvider(provider.i)
	get_RootVisualTarget(target.i)
	put_RootVisualTarget(target.i)
EndInterface 

;- ICoreWebView2ExperimentalCompositionController

DataSection
	IID_ICoreWebView2ExperimentalCompositionController:
	Data.l $584903B6
	Data.w $F79F, $4037
	Data.b $86, $76, $1B, $13, $D6, $78, $16, $3A
EndDataSection

Interface ICoreWebView2ExperimentalCompositionController Extends IUnknown
	get_UIAProvider(provider.i)
	get_RootVisualTarget(target.i)
	put_RootVisualTarget(target.i)
	SendMouseInput(eventKind.l, virtualKeys.l, mouseData.l, point.q)
	CompilerIf #PB_Compiler_Processor = #PB_Processor_x64
		CreateCoreWebView2PointerInfoFromPointerId(PointerId.l, parentWindow.i, transform.i, pointerInfo.i)
	CompilerElse
		CreateCoreWebView2PointerInfoFromPointerId(PointerId.l, parentWindow.i, transform_COREWEBVIEW2_MATRIX_4X4__11.f, transform_COREWEBVIEW2_MATRIX_4X4__12.f, transform_COREWEBVIEW2_MATRIX_4X4__13.f, transform_COREWEBVIEW2_MATRIX_4X4__14.f, transform_COREWEBVIEW2_MATRIX_4X4__21.f, transform_COREWEBVIEW2_MATRIX_4X4__22.f, transform_COREWEBVIEW2_MATRIX_4X4__23.f, transform_COREWEBVIEW2_MATRIX_4X4__24.f, transform_COREWEBVIEW2_MATRIX_4X4__31.f, transform_COREWEBVIEW2_MATRIX_4X4__32.f, transform_COREWEBVIEW2_MATRIX_4X4__33.f, transform_COREWEBVIEW2_MATRIX_4X4__34.f, transform_COREWEBVIEW2_MATRIX_4X4__41.f, transform_COREWEBVIEW2_MATRIX_4X4__42.f, transform_COREWEBVIEW2_MATRIX_4X4__43.f, transform_COREWEBVIEW2_MATRIX_4X4__44.f, pointerInfo.i)
	CompilerEndIf
	SendPointerInput(eventKind.l, pointerInfo.i)
	get_Cursor(Cursor.i)
	add_CursorChanged(eventHandler.i, token.i)
	remove_CursorChanged(token.q)
EndInterface 

;- Enum COREWEBVIEW2_MOUSE_EVENT_KIND
#COREWEBVIEW2_MOUSE_EVENT_KIND_HORIZONTAL_WHEEL = 526
#COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK = 515
#COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN = 513
#COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_UP = 514
#COREWEBVIEW2_MOUSE_EVENT_KIND_LEAVE = 675
#COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK = 521
#COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN = 519
#COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP = 520
#COREWEBVIEW2_MOUSE_EVENT_KIND_MOVE = 512
#COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK = 518
#COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN = 516
#COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_UP = 517
#COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL = 522
#COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK = 525
#COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOWN = 523
#COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_UP = 524

;- Enum COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE = 0
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON = 1
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON = 2
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT = 4
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL = 8
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON = 16
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1 = 32
#COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2 = 64

;- COREWEBVIEW2_MATRIX_4X4
Structure COREWEBVIEW2_MATRIX_4X4 Align #PB_Structure_AlignC
	_11.f
	_12.f
	_13.f
	_14.f
	_21.f
	_22.f
	_23.f
	_24.f
	_31.f
	_32.f
	_33.f
	_34.f
	_41.f
	_42.f
	_43.f
	_44.f
EndStructure

;- ICoreWebView2ExperimentalPointerInfo

DataSection
	IID_ICoreWebView2ExperimentalPointerInfo:
	Data.l $4BB4E46D
	Data.w $7D78, $47BD
	Data.b $BD, $D2, $4B, $77, $28, $8D, $C9, $49
EndDataSection

Interface ICoreWebView2ExperimentalPointerInfo Extends IUnknown
	get_PointerKind(PointerKind.i)
	put_PointerKind(PointerKind.l)
	get_PointerId(PointerId.i)
	put_PointerId(PointerId.l)
	get_FrameId(FrameId.i)
	put_FrameId(FrameId.l)
	get_PointerFlags(PointerFlags.i)
	put_PointerFlags(PointerFlags.l)
	get_PointerDeviceRect(PointerDeviceRect.i)
	CompilerIf #PB_Compiler_Processor = #PB_Processor_x64
		put_PointerDeviceRect(PointerDeviceRect.i)
	CompilerElse
		put_PointerDeviceRect(PointerDeviceRect_tagRECT_left.l, PointerDeviceRect_tagRECT_top.l, PointerDeviceRect_tagRECT_right.l, PointerDeviceRect_tagRECT_bottom.l)
	CompilerEndIf
	get_DisplayRect(DisplayRect.i)
	CompilerIf #PB_Compiler_Processor = #PB_Processor_x64
		put_DisplayRect(DisplayRect.i)
	CompilerElse
		put_DisplayRect(DisplayRect_tagRECT_left.l, DisplayRect_tagRECT_top.l, DisplayRect_tagRECT_right.l, DisplayRect_tagRECT_bottom.l)
	CompilerEndIf
	get_PixelLocation(PixelLocation.i)
	put_PixelLocation(PixelLocation.q)
	get_HimetricLocation(HimetricLocation.i)
	put_HimetricLocation(HimetricLocation.q)
	get_PixelLocationRaw(PixelLocationRaw.i)
	put_PixelLocationRaw(PixelLocationRaw.q)
	get_HimetricLocationRaw(HimetricLocationRaw.i)
	put_HimetricLocationRaw(HimetricLocationRaw.q)
	get_Time(Time.i)
	put_Time(Time.l)
	get_HistoryCount(HistoryCount.i)
	put_HistoryCount(HistoryCount.l)
	get_InputData(InputData.i)
	put_InputData(InputData.l)
	get_KeyStates(KeyStates.i)
	put_KeyStates(KeyStates.l)
	get_PerformanceCount(PerformanceCount.i)
	put_PerformanceCount(PerformanceCount.q)
	get_ButtonChangeKind(ButtonChangeKind.i)
	put_ButtonChangeKind(ButtonChangeKind.l)
	get_PenFlags(PenFlags.i)
	put_PenFlags(PenFlags.l)
	get_PenMask(PenMask.i)
	put_PenMask(PenMask.l)
	get_PenPressure(PenPressure.i)
	put_PenPressure(PenPressure.l)
	get_PenRotation(PenRotation.i)
	put_PenRotation(PenRotation.l)
	get_PenTiltX(PenTiltX.i)
	put_PenTiltX(PenTiltX.l)
	get_PenTiltY(PenTiltY.i)
	put_PenTiltY(PenTiltY.l)
	get_TouchFlags(TouchFlags.i)
	put_TouchFlags(TouchFlags.l)
	get_TouchMask(TouchMask.i)
	put_TouchMask(TouchMask.l)
	get_TouchContact(TouchContact.i)
	CompilerIf #PB_Compiler_Processor = #PB_Processor_x64
		put_TouchContact(TouchContact.i)
	CompilerElse
		put_TouchContact(TouchContact_tagRECT_left.l, TouchContact_tagRECT_top.l, TouchContact_tagRECT_right.l, TouchContact_tagRECT_bottom.l)
	CompilerEndIf
	get_TouchContactRaw(TouchContactRaw.i)
	CompilerIf #PB_Compiler_Processor = #PB_Processor_x64
		put_TouchContactRaw(TouchContactRaw.i)
	CompilerElse
		put_TouchContactRaw(TouchContactRaw_tagRECT_left.l, TouchContactRaw_tagRECT_top.l, TouchContactRaw_tagRECT_right.l, TouchContactRaw_tagRECT_bottom.l)
	CompilerEndIf
	get_TouchOrientation(TouchOrientation.i)
	put_TouchOrientation(TouchOrientation.l)
	get_TouchPressure(TouchPressure.i)
	put_TouchPressure(TouchPressure.l)
EndInterface 

;- Enum COREWEBVIEW2_POINTER_EVENT_KIND
#COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE = 587
#COREWEBVIEW2_POINTER_EVENT_KIND_DOWN = 582
#COREWEBVIEW2_POINTER_EVENT_KIND_ENTER = 585
#COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE = 586
#COREWEBVIEW2_POINTER_EVENT_KIND_UP = 583
#COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE = 581

;- ICoreWebView2ExperimentalCursorChangedEventHandler

DataSection
	IID_ICoreWebView2ExperimentalCursorChangedEventHandler:
	Data.l $9DA43CCC
	Data.w $26E1, $4DAD
	Data.b $B5, $6C, $D8, $96, $1C, $94, $C5, $71
EndDataSection

Interface ICoreWebView2ExperimentalCursorChangedEventHandler Extends IUnknown
	Invoke(sender.i, args.i)
EndInterface 

;- ICoreWebView2ExperimentalCompositionController2

DataSection
	IID_ICoreWebView2ExperimentalCompositionController2:
	Data.l $279AE616
	Data.w $B7CB, $4946
	Data.b $8D, $A3, $DC, $85, $36, $45, $D2, $BA
EndDataSection

Interface ICoreWebView2ExperimentalCompositionController2 Extends IUnknown
	get_SystemCursorId(SystemCursorId.i)
EndInterface 

;- ICoreWebView2ExperimentalCompositionController3

DataSection
	IID_ICoreWebView2ExperimentalCompositionController3:
	Data.l $B134916B
	Data.w $A104, $4D2A
	Data.b $95, $67, $C2, $FD, $53, $71, $43, $50
EndDataSection

Interface ICoreWebView2ExperimentalCompositionController3 Extends IUnknown
	DragEnter(dataObject.i, keyState.l, point.q, effect.i)
	DragLeave()
	DragOver(keyState.l, point.q, effect.i)
	Drop(dataObject.i, keyState.l, point.q, effect.i)
EndInterface 

;- ICoreWebView2ExperimentalController

DataSection
	IID_ICoreWebView2ExperimentalController:
	Data.l $3413543F
	Data.w $7A0E, $4B56
	Data.b $98, $C1, $7A, $F3, $A3, $74, $16, $CA
EndDataSection

Interface ICoreWebView2ExperimentalController Extends IUnknown
	get_RasterizationScale(scale.i)
	put_RasterizationScale(scale.d)
	get_ShouldDetectMonitorScaleChanges(value.i)
	put_ShouldDetectMonitorScaleChanges(value.l)
	add_RasterizationScaleChanged(eventHandler.i, token.i)
	remove_RasterizationScaleChanged(token.q)
	get_BoundsMode(BoundsMode.i)
	put_BoundsMode(BoundsMode.l)
EndInterface 

;- ICoreWebView2ExperimentalRasterizationScaleChangedEventHandler

DataSection
	IID_ICoreWebView2ExperimentalRasterizationScaleChangedEventHandler:
	Data.l $51560BE0
	Data.w $AD4, $4157
	Data.b $90, $CF, $E6, $DA, $D6, $38, $D8, $AA
EndDataSection

Interface ICoreWebView2ExperimentalRasterizationScaleChangedEventHandler Extends IUnknown
	Invoke(sender.i, args.i)
EndInterface 

;- Enum COREWEBVIEW2_BOUNDS_MODE
#COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS = 0
#COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE = 1

;- ICoreWebView2ExperimentalCreateCoreWebView2CompositionControllerCompletedHandler

DataSection
	IID_ICoreWebView2ExperimentalCreateCoreWebView2CompositionControllerCompletedHandler:
	Data.l $34B35AB6
	Data.w $3E59, $4FC4
	Data.b $A7, $23, $C, $4, $95, $3E, $3E, $13
EndDataSection

Interface ICoreWebView2ExperimentalCreateCoreWebView2CompositionControllerCompletedHandler Extends IUnknown
	Invoke(errorCode.l, webView.i)
EndInterface 

;- ICoreWebView2ExperimentalEnvironmentInterop

DataSection
	IID_ICoreWebView2ExperimentalEnvironmentInterop:
	Data.l $79455D4F
	Data.w $D28D, $4C3F
	Data.b $A7, $13, $13, $CA, $39, $3B, $D2, $E4
EndDataSection

Interface ICoreWebView2ExperimentalEnvironmentInterop Extends IUnknown
	GetProviderForHwnd(hwnd.i, provider.i)
EndInterface 

;- Enum COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND
#COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY = 0
#COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW = 1
#COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS = 2

;- ICoreWebView2Experimental2

DataSection
	IID_ICoreWebView2Experimental2:
	Data.l $CDAA2FCB
	Data.w $C2C0, $44F1
	Data.b $85, $7, $88, $A8, $59, $D7, $C3, $7D
EndDataSection

Interface ICoreWebView2Experimental2 Extends IUnknown
	SetVirtualHostNameToFolderMapping(hostName.s, folderPath.s, accessKind.l)
	ClearVirtualHostNameToFolderMapping(hostName.s)
EndInterface 

;- ICoreWebView2ExperimentalEnvironment

DataSection
	IID_ICoreWebView2ExperimentalEnvironment:
	Data.l $427A8887
	Data.w $1AB4, $4017
	Data.b $AE, $6E, $C6, $E6, $EB, $16, $C6, $64
EndDataSection

Interface ICoreWebView2ExperimentalEnvironment Extends IUnknown
	CreateCoreWebView2CompositionController(parentWindow.i, handler.i)
	CreateCoreWebView2PointerInfo(pointerInfo.i)
	GetProviderForHwnd(hwnd.i, provider.i)
	CreateWebResourceRequestDeprecated(Uri.s, Method.s, postData.i, Headers.s, request.i)
EndInterface 

